FROM nvcr.io/nvidia/nvhpc:24.5-devel-cuda12.4-ubuntu22.04
WORKDIR /opt
ENV DEBIAN_FRONTEND noninteractive

RUN \
    apt-get update        &&   \
    apt-get install --yes      \
    apbs                   \
    autoconf               \
    automake               \
    bc                     \
    bison                  \
    build-essential        \
    cmake                  \
    curl                   \
    fig2dev                \
    flex                   \
    g++                    \
    gcc                    \
    ghostscript            \
    gfortran               \
    git                    \
    indent                 \
    libaec-dev             \
    libblas-dev            \
    libboost-all-dev       \
    libbz2-dev             \
    libfftw3-dev           \
    libgmp-dev             \
    libgsl-dev             \
    libhdf5-mpi-dev        \
    libicu-dev             \
    liblapack-dev          \
    liblapacke-dev         \
    libmunge-dev           \
    libnetcdf-mpi-dev      \
    libnetcdff-dev         \
    libnum-ocaml           \
    libnum-ocaml-dev       \
    libpnetcdf-dev         \
    libssl-dev             \
    libsz2                 \
    libtool                \
    libxml2-dev            \
    lsb-release            \
    ocaml                  \
    ocaml-findlib          \
    ocamlbuild             \
    parallel               \
    pkg-config             \
    slurm-client           \
    tar                    \
    texinfo                \
    unzip                  \
    vim                    \
    wget                   \
    zlib1g                 \
    zlib1g-dev          && \    
    apt-get clean all
ENV LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH

# Install MPICH (required for perlmutter, check recipe version)
ARG mpich=4.2.2
ARG mpich_prefix=mpich-$mpich
RUN \
    wget https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz && \
    tar xvzf $mpich_prefix.tar.gz                                           && \
    cd $mpich_prefix                                                        && \
    ./configure  && \
    make -j 16                                                              && \
    make install                                                            && \
    make clean                                                              && \
    cd ..                                                                   && \
    rm -rf $mpich_prefix
RUN /sbin/ldconfig

# Install miniconda (working)
ENV installer=Miniconda3-py39_24.5.0-0-Linux-x86_64.sh
RUN wget https://repo.anaconda.com/miniconda/$installer && \
    /bin/bash $installer -b -p /opt/miniconda3          && \
    rm -rf $installer
ENV PATH=/opt/miniconda3/bin:$PATH
RUN conda install -y numpy scipy matplotlib setuptools mpi4py scikit-learn joblib

# Update CMake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.29.6/cmake-3.29.6-linux-x86_64.tar.gz && \
    tar xzf cmake-3.29.6-linux-x86_64.tar.gz && \
    export PATH=/opt/cmake-3.29.6-linux-x86_64/bin:$PATH